### ISSUE TITLE
Plays loops more times than it says

### ISSUE THREAD

**Issue by protheory8** [dyc3/stream-autodj#5]
Prints `Repeating loop 7 times` but plays it 8 times.

**Comment by cbondurant** [comment]
I'm not able to replicate this, I counted the loops myself and when it reported 10 loops there were 10 that played. Is it possible that you mistook a loop transition for another playing of the loop itself?

**Comment by protheory8** [comment]
I don't think so because I changed songs to sound with a start and with 1 loop without any transitions. I will try to count them again.

**Comment by protheory8** [comment]
I was able to replicate the issue.

**Comment by dyc3** [comment]
Does it happen for one song or for any of them?

**Comment by dyc3** [comment]
I think I know why. In the Iterator implementation for the repeat source, the first if clause in `next` doesn't run `self.count_remaining -= 1;`.

**Comment by protheory8** [comment]
dyc3, did you manage to replicate the issue?

**Comment by protheory8** [comment]
If I recall correctly, the first if clause just plays one song until the end, so it doesn't need to have it.

**Comment by dyc3** [comment]
I haven't exactly tested it, I'm just kinda spitballing.

**Comment by protheory8** [comment]
Changing `else if self.count_remaining > 1` to `else if self.count_remaining > 2` fixes the issue for me and I have no idea why.

**Comment by dyc3** [comment]
Ok, I looked at it a little more, and I can reproduce it. It happens because `count_remaining` is not decremented when it plays the first time around. So it doesn't consume one of it's uses. Will commit a fix in a sec

**Comment by protheory8** [comment]
@dyc3 Not sure if that can be considered a real issue, but `Song::read_segment` is currently hardcoded to open only `.ogg` files.

**Comment by dyc3** [comment]
Open a separate issue for it

**Comment by cbondurant** [comment]
I hate to reopen a closed issue, but I did some more checking, using a set of audio files generated by `espeak` that simply were the words "start" "loop" and "end"

Using this to count, the loop actually now plays one less time than reported. I think this issue needs more investigation before it can be closed. 

Attached is a zip of the files I used.
[wav_test.zip](https://github.com/dyc3/stream-autodj/files/5029262/wav_test.zip)

**Comment by dyc3** [comment]
Yeah I can confirm. Whoops

**Comment by dyc3** [comment]
I think one of the song ends that I have includes a full loop before the actual end in the end segment, so that might be what tripped us up.

**Comment by protheory8** [comment]
OK, I did some small investigation and I think I know the reason. It seems like this program plays the loop more times than it says when the song has no `end` segment. When there is `end` segment, everything is OK.

**Comment by protheory8** [comment]
I previously tested only with `start` and `loop` segment, so that's why it was playing `n + 1` times.

**Comment by protheory8** [comment]
Can someone confirm?

**Comment by dyc3** [comment]
This is intentional, it should play the loop one more time as it crossfades with a zero source, effectively a fade out. It's a bug if it doesn't fade out

**Comment by protheory8** [comment]
It seems like fade out doesn't work on really short loops on my PC, otherwise longer loops work fine.

**Comment by protheory8** [comment]
Didn't know it was intentional btw, my bad.

**Comment by dyc3** [comment]
Yeah, the problem with the fade out is that it uses a fixed duration to crossfade, instead of using the duration of the segment.
