### ISSUE TITLE
Reason for `song_` prefix? 

### ISSUE THREAD

**Issue by cbondurant** [dyc3/stream-autodj#8]
I was looking into making the song initialization more robust and able to recover from errors that should not result in panic (single files that are not valid audio files being skipped instead of causing a panic for instance).

While working on this I notice that the `song_` prefix is both expected, but not enforced. You can currently have any prefix at all, eg `test_`, `song_`, `fake_`, etc. 

Should the requirement for the prefix be enforced, or should it be removed entirely? repaced with a `songname_segmentID.format` syntax instead?

**Comment by dyc3** [comment]
No particular reason. It might be better to parse the segment id by grabbing the last `_` split, and concat the first splits to use for the song id.
